title: 'Bioethics Advisory Committee'
title-abbreviated: BAC
description: Description
url: 'https://www.bioethics-singapore.org'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
is_government: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
collections:
    who-we-are:
        output: true
    bioethics-resource:
        output: true
    activities:
        output: true
resources_name: publications
favicon: /images/Bioeth-4-1.ico
google_analytics: null
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
